language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

install:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

# do not run performance tests as they take too long to run and are killed by Travis
branches:
  except:
    - perf-tests
